name: flutter_son_emlak
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  firebase_analytics: ^8.1.2
  image_cropper: ^1.4.1
  cloud_firestore: ^2.2.2
  image_picker: ^0.8.0+3
  geolocator: ^7.1.0
  geocoding: ^2.0.0
  camera: ^0.8.1+3
  uuid: ^3.0.4
  path_provider: ^2.0.2
  location: ^4.3.0
  firebase_storage: ^8.1.3
  timeago: ^3.1.0
  photo_view: ^0.11.1
  pinch_zoom: ^0.1.0
  firebase_messaging: ^10.0.2
  animated_bottom_navigation_bar: ^0.3.2
  flutter_local_notifications: ^6.0.0
  progress_state_button: ^1.0.3
  google_sign_in: ^5.0.4
  image: ^3.0.2
  cupertino_icons: ^1.0.3
  fluttertoast: ^8.0.7
  intl: ^0.17.0
  animated_text_kit: ^4.2.1
  flutter_audio_recorder2: ^0.0.2
  audioplayers: ^0.19.1
  video_player: ^2.1.10
  #slide_to_act: ^2.0.1
  intro_slider: ^3.0.2
  google_maps_flutter: ^2.0.6
  cupertino_stepper: ^0.2.0
  google_fonts: ^2.1.0
  carousel_slider: ^4.0.0
  smooth_page_indicator: 0.3.0-nullsafety.0
  cached_network_image: ^3.1.0
  get_it: ^7.2.0
  slide_to_confirm: ^1.1.0
  simple_ripple_animation: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf

  assets:
    - assets/images/
    - assets/sehir1.json
    - assets/ilce1.json
    - assets/mahalle1.json
    - assets/Kategori.json
    - assets/Tip.json
    #- assets/images/google_signin_button1.png
    #- assets/images/scard.png
    #- assets/images/sccard.png
    #- assets/images/logo.png
    #- assets/images/logo2.png
    #- assets/images/sscard.png
    #- assets/images/manzara.jpg

